#!groovy
// Build RMQ image
properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'master'
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage("docker login") {
            steps {
                echo "====================     docker login     ======================="
                withCredentials([usernamePassword(credentialsId: 'jenkins-mhaz223-cred', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh "docker login -u $USERNAME -p $PASSWORD"
                }
            }
        }
        stage("Build Docker image") {
            steps {
                echo "==================== start building image ======================="
                dir ('RMQ/docker/rabbitmq') {
                    sh 'docker build -t mhaz223/container-rmq1:latest . '
                }
            }
        }
        stage("docker push") {
            steps {
                echo "==================== start pushing image  ======================="
                sh 'docker push mhaz223/container-rmq1:latest'
            }
        }
    }
}
